### ISSUE TITLE
The metal material does not self-shadowing when using roughness texture.

### ISSUE THREAD

**Issue by serkkz** [Moguri/panda3d-simplepbr#42] opened 2022-05-20 19:29 UTC
I have such material.

```python
metal = Material("brick")
metal.set_metallic(1)
metal.set_roughness(0.45)
````
This gives the following:
![1](https://user-images.githubusercontent.com/17797036/169598019-8c97baef-1cc8-40cb-abad-b9f6e9901d8d.png)

It can be seen that the sphere has artifacts in self-shadowing. I also found out that the problem is related to the roughness map, maybe I'm using it incorrectly.

```python
roughness_tex = loader.loadTexture("tex/metal/roughness.png")
roughness_tex.set_magfilter(SamplerState.FT_linear_mipmap_linear)
roughness_tex.set_minfilter(SamplerState.FT_linear_mipmap_linear)
roughness_tex.set_wrap_u(Texture.WM_repeat)
roughness_tex.set_wrap_v(Texture.WM_repeat)

metal_stage = TextureStage('metal_stage')
metal_stage.set_mode(TextureStage.M_selector)
```
![2](https://user-images.githubusercontent.com/17797036/169599422-3ff768c2-8854-48b5-8be7-3d34d1a79baf.png)

It looks like this without ambient lighting. Which seems normal to me.

**Comment by serkkz** [comment] 2022-05-21 12:55
It seems that I was mistaken in the fact that the metal flag affects this problem.

This is just a duplicate of this problem. [19](https://github.com/Moguri/panda3d-simplepbr/issues/19)
My problem is applying a roughness texture.

**Comment by Moguri** [comment] 2023-05-19 05:07
Closing as duplicate of #19

**Closed by Moguri** 2023-05-19 05:07 UTC
